version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: custom-app-name
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
    depends_on:
      - mysql
